version: '3'
services:
  client:
    image: ${REGISTRY:-cardin21}/multi-client:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: ./client
      dockerfile: Dockerfile
    mem_limit: 128m
    hostname: client
  server:
    image: ${REGISTRY:-cardin21}/multi-server:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: ./server
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: ${REGISTRY:-cardin21}/multi-worker:${PLATFORM:-linux}-${TAG:-latest}
    build: 
      context: ./worker
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: 'rallycoding/multi-nginx'
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
