apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
# DEFAULT FOR KEY VALUE PAIRS
# kubectl apply -f secret.yaml
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=
