apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  # Lurl vers la base de données est le nom du service
  # La config doit être d'abord dans le cluster avant le déploiement
  database_url: mongodb-service
