name: "Intégration Continue - Pull Request"
on:
  pull_request:
    branches:
      - master

jobs:
  code-tests:
    runs-on: [self-hosted, is-enabled]
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{github.event.pull_request.head.ref}}